[project]
name = "converse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.44",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.3",
]
